name: Testing workflow variable
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  cloud: google-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env: 
      greating: hello
    steps:
      - name: "Say hello Noyon. It's  Wednesday"
        run: echo "$greating $first_name is using $cloud"
        env:
          first_name: Noyon
